version: '3.8'

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - backend/.env
    restart: always

  backend:
    image: djalyarim/foodgram_backend:latest
    restart: always
    depends_on:
      - db
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    env_file:
    - backend/.env

  frontend:
    image: djalyarim/foodgram_frontend:latest
    volumes:
      - ./frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.19.3
    ports:
      - 80:80
    volumes:
      - static_value:/static/
      - media_value:/media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      - ./docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
    restart: always
    depends_on:
      - frontend

volumes:
  postgres_data:
  static_value:
  media_value: